Setup:
  input_path: '/vols/cms/lcr119/offline/HiggsCP/data/production_v2/ShuffleMerge/mt' # Medium (Standard Dataset)
Features:
  train: ['pt_1', 'pt_2', 'eta_1', 'eta_2', 'phi_1', 'phi_2', # individual 4-vectors
          'met_pt','met_dphi_1', 'met_dphi_2', # met information
          'dR', 'dphi', 'pt_tt', 'm_vis', 'pt_vis', 'FastMTT_mass', # pair quantities
          'mt_1', 'mt_2', 'mt_lep', 'mt_tot', # transverse masses
          'jpt_1', 'jpt_2', 'jeta_1', 'jeta_2', # individual jets
          'mjj', 'jdeta', 'dijetpt', # dijet quantities
          'n_jets', 'n_bjets'] # global jet information
  weight: 'class_weight'
  truth: 'class_label'