Setup:
  input_path: '/vols/cms/lcr119/offline/HiggsCP/data/earlyrun3/ShuffleMerge_tight/tt'
  model_outputs: 'XGB_Models/EarlyRun3/'
  model_dir_name: 'model_opt_tight'

param: {
        'objective': 'multi:softmax',
        'n_estimators': 661,
        'lambda': 0.1412650013482672,
        'subsample': 0.6163346049164129,
        'colsample_bytree': 0.8433665616684342,
        'learning_rate': 0.0627106185884069,
        'max_depth': 5,
        'min_child_weight': 4
      }





Features:
  train: ['pt_1', 'pt_2', 'eta_1', 'eta_2', 'phi_1', 'phi_2', 'dR', 'pt_tt',
            'mt_1', 'mt_2', 'mt_lep', 'mt_tot', 'met_pt',
            'met_dphi_1', 'met_dphi_2', 'dphi', 'm_vis', 'pt_vis', 'n_jets',
            'n_bjets', 'mjj', 'jdeta', 'dijetpt', 'jpt_1', 'jpt_2', 'jeta_1',
            'jeta_2', 'FastMTT_Mass']
  weight: 'class_weight'
  truth: 'class_label'
