Setup:
  input_path: '/vols/cms/lcr119/offline/HiggsCP/data/earlyrun3/ShuffleMerge/tt'
  model_outputs: 'XGB_Models/Full2022/'
  model_name: 'model_test'

param: {
        'objective': 'multi:softmax',
        'n_estimators': 837,
        'max_depth': 5,
        'learning_rate': 0.0504790888140139,
        'lambda': 4.3322006949756574e-08,
        'min_child_weight': 5,
        'subsample': 0.6641249000584662,
        'colsample_bytree': 0.325022661012661
      }


Features:
  train: ['pt_1', 'pt_2', 'eta_1', 'eta_2', 'phi_1', 'phi_2', 'dR', 'pt_tt',
            'mt_1', 'mt_2', 'mt_lep', 'mt_tot', 'met_pt',
            'met_dphi_1', 'met_dphi_2', 'dphi', 'm_vis', 'pt_vis', 'n_jets',
            'n_bjets', 'mjj', 'jdeta', 'dijetpt', 'jpt_1', 'jpt_2', 'jeta_1',
            'jeta_2', 'FastMTT_Mass']
  weight: 'class_weight'
  truth: 'class_label'
