Setup:
  input_path: '/vols/cms/lcr119/offline/HiggsCP/data/earlyrun3/ShuffleMerge_Vtight/tt'
  model_outputs: 'XGB_Models/Full2022/'
  model_dir_name: 'model_opt_vtight'

param: {
        'objective': 'multi:softmax',
        'n_estimators': 387,
        'lambda': 2.203405884122426e-05,
        'subsample': 0.7160170778419747,
        'colsample_bytree': 0.6839469685236267,
        'learning_rate': 0.1599237489599659,
        'max_depth': 4,
        'min_child_weight': 9
      }


Features:
  train: ['pt_1', 'pt_2', 'eta_1', 'eta_2', 'phi_1', 'phi_2', 'dR', 'pt_tt',
            'mt_1', 'mt_2', 'mt_lep', 'mt_tot', 'met_pt',
            'met_dphi_1', 'met_dphi_2', 'dphi', 'm_vis', 'pt_vis', 'n_jets',
            'n_bjets', 'mjj', 'jdeta', 'dijetpt', 'jpt_1', 'jpt_2', 'jeta_1',
            'jeta_2', 'FastMTT_Mass']
  weight: 'class_weight'
  truth: 'class_label'
