Setup:
  input_path: '/vols/cms/lcr119/offline/HiggsCP/data/earlyrun3/ShuffleMerge/tt'
  model_outputs: 'XGB_Models/EarlyRun3/tt'
  model_dir_name: 'model_opt_medium'

param: {
        'objective': 'multi:softmax',
        'n_estimators': 283,
        'lambda': 0.06657131112566837,
        'subsample': 0.7428150366090029,
        'colsample_bytree': 0.5427881225663449,
        'learning_rate': 0.08875949781591855,
        'max_depth': 6,
        'min_child_weight': 2
      }

Features:
  train: ['pt_1', 'pt_2', 'eta_1', 'eta_2', 'phi_1', 'phi_2', # individual 4-vectors
          'met_pt','met_dphi_1', 'met_dphi_2', # met information
          'dR', 'dphi', 'pt_tt', 'm_vis', 'pt_vis', 'FastMTT_Mass', # pair quantities
          'mt_1', 'mt_2', 'mt_lep', 'mt_tot', # transverse masses
          'jpt_1', 'jpt_2', 'jeta_1', 'jeta_2', # individual jets
          'mjj', 'jdeta', 'dijetpt', # dijet quantities
          'n_jets', 'n_bjets'] # global jet information
  weight: 'class_weight'
  truth: 'class_label'
