Setup:
  input_path: '/vols/cms/lcr119/offline/HiggsCP/data/ShuffleMerge/2022/tt'
  model_outputs: 'DNN_Models/Testing/'
  model_name: 'model_test'

training_setup:
  epochs: 15
  batch_size: 256

param: {
        'dropout_rate': 0.2,
        'learning_rate': 0.001,
      }

Features:
  train: ['pt_1', 'pt_2', 'eta_1', 'eta_2', 'phi_1', 'phi_2', 'dR', 'pt_tt',
            'pt_tt_met', 'mt_1', 'mt_2', 'mt_lep', 'mt_tot', 'met_pt',
            'met_dphi_1', 'met_dphi_2', 'dphi', 'm_vis', 'pt_vis', 'n_jets',
            'n_bjets', 'mjj', 'jdeta', 'dijetpt', 'jpt_1', 'jpt_2', 'jeta_1',
            'jeta_2', 'FastMTT_Mass']
  weight: 'NN_weight'
  truth: 'class_label'
