Setup:
  eras: ['Run3_2022'] #, 'Run3_2022EE', 'Run3_2023', 'Run3_2023BPix'] # Eras to be used
  channel: 'tt'
  input: '/vols/cms/lcr119/offline/HiggsCP/HiggsDNA/output/production' # HiggsDNA output
  output: '/vols/cms/lcr119/offline/HiggsCP/data/ProdDev/ShuffleMerge' # ShuffleMerge output
  skim_output: '/vols/cms/lcr119/offline/HiggsCP/data/ProdDev/PreSelected' # Output for selected (and gen matched) events
  proc_output: '/vols/cms/lcr119/offline/HiggsCP/data/ProdDev/Weighted' # Temporary output for weighted/labelled events

Selection: # Selection to be applied
  vsjet_1: 5 # Medium
  vsjet_2: 5 # Medium
  vse_1: 2 # VVLoose
  vse_2: 2 # VVLoose
  vsmu_1: 1 # VLoose
  vsmu_2: 1 # VLoose
  triggers: ['trg_doubletau', 'trg_doubletauandjet']

# Variables that will be kept in dataframes
Features: ['pt_1', 'pt_2', 'eta_1', 'eta_2', 'phi_1', 'phi_2', 'dR', 'pt_tt',
            'mt_1', 'mt_2', 'mt_lep', 'mt_tot', 'met_pt',
            'met_dphi_1', 'met_dphi_2', 'dphi', 'm_vis', 'pt_vis', 'n_jets',
            'n_bjets', 'mjj', 'jdeta', 'dijetpt', 'jpt_1', 'jpt_2', 'jeta_1',
            'jeta_2', 'rawDeepTau2018v2p5VSjet_1', rawDeepTau2018v2p5VSjet_2,
            'FastMTT_Mass', #'svfitMass', 'svfitMass_err', # Mass info
            'weight', 'run', 'lumi', 'event'] # Run info
