Params:
  Luminosity: 9451
Process:
  DY:
    DYto2L_M_50_1J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 69398459.0
      x_sec: 6282.6
    DYto2L_M_50_2J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 69398459.0
      x_sec: 6282.6
    DYto2L_M_50_3J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 69398459.0
      x_sec: 6282.6
    DYto2L_M_50_4J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 69398459.0
      x_sec: 6282.6
    DYto2L_M_50_madgraphMLM:
      filter_eff: 1.0
      n_eff: 69398459.0
      x_sec: 6282.6
  Diboson:
    WW:
      filter_eff: 1.0
      n_eff: 16545000
      x_sec: 122.27052
    WZ:
      filter_eff: 1.0
      n_eff: 8379000
      x_sec: 41.1474
    ZZ:
      filter_eff: 1.0
      n_eff: 1254000
      x_sec: 19.431
  Electron_DATA:
    EGamma0_Run2023D_v1:
      extrapolation_factor: 1.1
    EGamma0_Run2023D_v2:
      extrapolation_factor: 1.1
    EGamma1_Run2023D_v1:
      extrapolation_factor: 1.1
    EGamma1_Run2023D_v2:
      extrapolation_factor: 1.1
  Muon_DATA:
    Muon0_Run2023D_v1:
      extrapolation_factor: 1.1
    Muon0_Run2023D_v2:
      extrapolation_factor: 1.1
    Muon1_Run2023D_v1:
      extrapolation_factor: 1.1
    Muon1_Run2023D_v2:
      extrapolation_factor: 1.1
  ST:
    ST_tW_antitop_2L2Nu:
      filter_eff: 1.0
      n_eff: 2487898.0
      x_sec: 3.8
    ST_tW_antitop_LNu2Q:
      filter_eff: 1.0
      n_eff: 5146462.0
      x_sec: 15.9
    ST_tW_top_2L2Nu:
      filter_eff: 1.0
      n_eff: 2478922.0
      x_sec: 3.8
    ST_tW_top_LNu2Q:
      filter_eff: 1.0
      n_eff: 4943196.0
      x_sec: 15.8
  TTBar:
    TTto2L2Nu:
      filter_eff: 1.0
      n_eff: 24357456.0
      x_sec: 98.04387875606875
    TTto4Q:
      filter_eff: 1.0
      n_eff: 52422350.0
      x_sec: 419.8071644141188
    TTtoLNu2Q:
      filter_eff: 1.0
      n_eff: 76050494.0
      x_sec: 405.74895682981236
  Tau_DATA:
    Tau_Run2023D_v1:
      extrapolation_factor: 1.1
    Tau_Run2023D_v2:
      extrapolation_factor: 1.1
  VBFH:
    VBFHToTauTau_UncorrelatedDecay_Filtered:
      filter_eff: 0.4091
      n_eff: 7048003
      x_sec: 0.2558
  VH:
    WminusHToTauTau_UncorrelatedDecay_Filtered:
      filter_eff: 0.3944
      n_eff: 718725
      x_sec: 0.03561
    WplusHToTauTau_UncorrelatedDecay_Filtered:
      filter_eff: 0.3743
      n_eff: 952493
      x_sec: 0.05575
    ZHToTauTau_UncorrelatedDecay_Filtered:
      filter_eff: 0.3933
      n_eff: 1007812
      x_sec: 0.0592
  WJets:
    WtoLNu_1J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 94639090.0
      x_sec: 63425.09999999999
    WtoLNu_2J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 94639090.0
      x_sec: 63425.09999999999
    WtoLNu_3J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 94639090.0
      x_sec: 63425.09999999999
    WtoLNu_4J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 94639090.0
      x_sec: 63425.09999999999
    WtoLNu_madgraphMLM:
      filter_eff: 1.0
      n_eff: 94639090.0
      x_sec: 63425.09999999999
  ggH:
    GluGluHTo2Tau_UncorrelatedDecay_CPodd_Filtered_ProdAndDecay:
      filter_eff: 0.3848
      n_eff: 26842817
      x_sec: 3.2759
    GluGluHTo2Tau_UncorrelatedDecay_MM_Filtered_ProdAndDecay:
      filter_eff: 0.3848
      n_eff: 26842817
      x_sec: 3.2759
    GluGluHTo2Tau_UncorrelatedDecay_SM_Filtered_ProdAndDecay:
      filter_eff: 0.3847
      n_eff: 26842817
      x_sec: 3.2759
