Params:
  Luminosity: 17794
Process:
  DY:
    DYto2L_M_50_1J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 130559088.0
      x_sec: 6282.6
    DYto2L_M_50_2J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 130559088.0
      x_sec: 6282.6
    DYto2L_M_50_3J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 130559088.0
      x_sec: 6282.6
    DYto2L_M_50_4J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 130559088.0
      x_sec: 6282.6
    DYto2L_M_50_madgraphMLM:
      filter_eff: 1.0
      n_eff: 130559088.0
      x_sec: 6282.6
  Diboson:
    WW:
      filter_eff: 1.0
      n_eff: 33507000
      x_sec: 122.27052
    WZ:
      filter_eff: 1.0
      n_eff: 16770000
      x_sec: 41.1474
    ZZ:
      filter_eff: 1.0
      n_eff: 2517000
      x_sec: 19.431
  Electron_DATA:
    EGamma0_Run2023C_v1:
      extrapolation_factor: 1.1
    EGamma0_Run2023C_v2:
      extrapolation_factor: 1.1
    EGamma0_Run2023C_v3:
      extrapolation_factor: 1.1
    EGamma0_Run2023C_v4:
      extrapolation_factor: 1.1
    EGamma1_Run2023C_v1:
      extrapolation_factor: 1.1
    EGamma1_Run2023C_v2:
      extrapolation_factor: 1.1
    EGamma1_Run2023C_v3:
      extrapolation_factor: 1.1
    EGamma1_Run2023C_v4:
      extrapolation_factor: 1.1
  Muon_DATA:
    Muon0_Run2023C_v1:
      extrapolation_factor: 1.1
    Muon0_Run2023C_v2:
      extrapolation_factor: 1.1
    Muon0_Run2023C_v3:
      extrapolation_factor: 1.1
    Muon0_Run2023C_v4:
      extrapolation_factor: 1.1
    Muon1_Run2023C_v1:
      extrapolation_factor: 1.1
    Muon1_Run2023C_v2:
      extrapolation_factor: 1.1
    Muon1_Run2023C_v3:
      extrapolation_factor: 1.1
    Muon1_Run2023C_v4:
      extrapolation_factor: 1.1
  ST:
    ST_tW_antitop_2L2Nu:
      filter_eff: 1.0
      n_eff: 4906798.0
      x_sec: 3.8
    ST_tW_top_2L2Nu:
      filter_eff: 1.0
      n_eff: 4984812.0
      x_sec: 3.8
    ST_tW_top_LNu2Q:
      filter_eff: 1.0
      n_eff: 9649924.0
      x_sec: 15.8
  TTBar:
    TTto2L2Nu:
      filter_eff: 1.0
      n_eff: 47713334.0
      x_sec: 98.04387875606875
    TTto4Q:
      filter_eff: 1.0
      n_eff: 104112654.0
      x_sec: 419.8071644141188
    TTtoLNu2Q:
      filter_eff: 1.0
      n_eff: 151416926.0
      x_sec: 405.74895682981236
  Tau_DATA:
    Tau_Run2023C_v1:
      extrapolation_factor: 1.1
    Tau_Run2023C_v2:
      extrapolation_factor: 1.1
    Tau_Run2023C_v3:
      extrapolation_factor: 1.1
    Tau_Run2023C_v4:
      extrapolation_factor: 1.1
  VBFH:
    VBFHToTauTau_UncorrelatedDecay_Filtered:
      filter_eff: 0.4091
      n_eff: 12453012
      x_sec: 0.2558
  VH:
    WminusHToTauTau_UncorrelatedDecay_Filtered:
      filter_eff: 0.3944
      n_eff: 1248957
      x_sec: 0.03561
    WplusHToTauTau_UncorrelatedDecay_Filtered:
      filter_eff: 0.3743
      n_eff: 1802553
      x_sec: 0.05575
    ZHToTauTau_UncorrelatedDecay_Filtered:
      filter_eff: 0.3933
      n_eff: 1803008
      x_sec: 0.0592
  WJets:
    WtoLNu_1J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 191075090.0
      x_sec: 63425.09999999999
    WtoLNu_2J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 191075090.0
      x_sec: 63425.09999999999
    WtoLNu_3J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 191075090.0
      x_sec: 63425.09999999999
    WtoLNu_4J_madgraphMLM:
      filter_eff: 1.0
      n_eff: 191075090.0
      x_sec: 63425.09999999999
    WtoLNu_madgraphMLM:
      filter_eff: 1.0
      n_eff: 191075090.0
      x_sec: 63425.09999999999
  ggH:
    GluGluHTo2Tau_UncorrelatedDecay_CPodd_Filtered_ProdAndDecay:
      filter_eff: 0.3848
      n_eff: 51778511
      x_sec: 3.2759
    GluGluHTo2Tau_UncorrelatedDecay_MM_Filtered_ProdAndDecay:
      filter_eff: 0.3848
      n_eff: 51778511
      x_sec: 3.2759
    GluGluHTo2Tau_UncorrelatedDecay_SM_Filtered_ProdAndDecay:
      filter_eff: 0.3847
      n_eff: 51778511
      x_sec: 3.2759
