# ************* Run 3 2023BPix  *************

# Samples to use for tau-tau channel
samples_tt: 
  'Tau_Run2023D_v1':
    data: true
    extrapolation_factor: 1.0
    label: 2
    x_sec: -1
    n_eff: -1
    process: 'QCD'
    lumi: 9451
    era: 'Run3_2023BPix'
  'Tau_Run2023D_v2':
    data: true
    extrapolation_factor: 1.0
    label: 2
    x_sec: -1
    n_eff: -1
    process: 'QCD'
    lumi: 9451
    era: 'Run3_2023BPix'
  'DYto2L_M-50_madgraphMLM':
    data: false
    label: 0
    x_sec: 6282.6
    n_eff: 69398459
    process: 'DY'
    lumi: 9451
    era: 'Run3_2023BPix'
  'DYto2L_M-50_1J_madgraphMLM':
    data: false
    label: 0
    x_sec: 6282.6
    n_eff: 69398459
    process: 'DY'
    lumi: 9451
    era: 'Run3_2023BPix'
  'DYto2L_M-50_2J_madgraphMLM':
    data: false
    label: 0
    x_sec: 6282.6
    n_eff: 69398459
    process: 'DY'
    lumi: 9451
    era: 'Run3_2023BPix'
  'DYto2L_M-50_3J_madgraphMLM':
    data: false
    label: 0
    x_sec: 6282.6
    n_eff: 69398459
    process: 'DY'
    lumi: 9451
    era: 'Run3_2023BPix'
  'DYto2L_M-50_4J_madgraphMLM':
    data: false
    label: 0
    x_sec: 6282.6
    n_eff: 69398459
    process: 'DY'
    lumi: 9451
    era: 'Run3_2023BPix'
  'GluGluHTo2Tau_UncorrelatedDecay_SM_Filtered_ProdAndDecay':
    data: false
    label: 11
    x_sec: 3.276
    n_eff: 26842817
    process: 'Higgs'
    filter_eff: 0.3847
    lumi: 9451
    era: 'Run3_2023BPix'
  'GluGluHTo2Tau_UncorrelatedDecay_MM_Filtered_ProdAndDecay':
    data: false
    label: 11
    x_sec: 3.276
    n_eff: 26842817
    process: 'Higgs'
    filter_eff: 0.3847
    lumi: 9451
    era: 'Run3_2023BPix'
  'GluGluHTo2Tau_UncorrelatedDecay_CPodd_Filtered_ProdAndDecay':
    data: false
    label: 11
    x_sec: 3.276
    n_eff: 26842817
    process: 'Higgs'
    filter_eff: 0.3847
    lumi: 9451
    era: 'Run3_2023BPix'
  'VBFHToTauTau_UncorrelatedDecay_Filtered':
    data: false
    label: 12
    x_sec: 0.2558
    n_eff: 7048003
    process: 'Higgs'
    filter_eff: 0.4095
    lumi: 9451
    era: 'Run3_2023BPix'
