# ************* Run 3 2023 *************

Params:
  Luminosity: 17794

# Processes to include for the MuTau Channel
Channel_mt:
  'DY': {gen_match: ['tau', 'lep', 'jet'], label: [0, 2, 2], proc_id: [11, 12, 13]}
  'ggH': {gen_match: false, label: 1, proc_id: 100}
  'VBFH': {gen_match: false, label: 1, proc_id: 101}
  'TTBar': {gen_match: ['tau', 'jet'], label: [0, 2], proc_id: [21, 23]}
  'ST': {gen_match: ['tau', 'jet'], label: [0, 2], proc_id: [31, 33]}
  'WJets': {gen_match: ['jet'], label: [2], proc_id: [43]}
  'Diboson': {gen_match: ['tau', 'jet'], label: [0, 2], proc_id: [51, 53]}
  'Muon_DATA': {gen_match: false, label: 2, proc_id: 0}

# Processes to include for the ETau Channel
Channel_et:
  'DY': {gen_match: ['tau', 'lep', 'jet'], label: [0, 2, 2], proc_id: [11, 12, 13]}
  'ggH': {gen_match: false, label: 1, proc_id: 100}
  'VBFH': {gen_match: false, label: 1, proc_id: 101}
  'TTBar': {gen_match: ['tau', 'jet'], label: [0, 2], proc_id: [21, 23]}
  'ST': {gen_match: ['tau', 'jet'], label: [0, 2], proc_id: [31, 33]}
  'WJets': {gen_match: ['jet'], label: [2], proc_id: [43]}
  'Diboson': {gen_match: ['tau', 'jet'], label: [0, 2], proc_id: [51, 53]}
  'Electron_DATA': {gen_match: false, label: 2, proc_id: 0}

# Processes to include for the TauTau Channel (Simple Estimate)
# Channel_tt:
#   'DY': {gen_match: false, label: 0, proc_id: 11}
#   'ggH': {gen_match: false, label: 1, proc_id: 100}
#   'VBFH': {gen_match: false, label: 1, proc_id: 101}
#   'Tau_DATA': {gen_match: false, label: 2, proc_id: 0}

# Processes to include for the TauTau Channel (Full QCD Estimate)
Channel_tt:
  'DY': {gen_match: ['tau', 'lep', 'jet'], label: [0, 2, 2], proc_id: [11, 12, 13]}
  'ggH': {gen_match: false, label: 1, proc_id: 100}
  'VBFH': {gen_match: false, label: 1, proc_id: 101}
  'TTBar': {gen_match: ['tau', 'jet'], label: [0, 2], proc_id: [21, 23]}
  'ST': {gen_match: ['tau', 'jet'], label: [0, 2], proc_id: [31, 33]}
  'WJets': {gen_match: ['jet'], label: [2], proc_id: [43]}
  'Diboson': {gen_match: ['tau', 'jet'], label: [0, 2], proc_id: [51, 53]}
  'Tau_DATA': {gen_match: false, label: 2, proc_id: 0}

# Datasets and information for the processes
Process:
  # Drell Yan Samples
  'DY':
    'DYto2L_M-50_madgraphMLM': {x_sec: 6282.6, n_eff: 130559088}
    'DYto2L_M-50_1J_madgraphMLM': {x_sec: 6282.6, n_eff: 130559088}
    'DYto2L_M-50_2J_madgraphMLM': {x_sec: 6282.6, n_eff: 130559088}
    'DYto2L_M-50_3J_madgraphMLM': {x_sec: 6282.6, n_eff: 130559088}
    'DYto2L_M-50_4J_madgraphMLM': {x_sec: 6282.6, n_eff: 130559088}
  # Gluon Fusion Higgs Samples
  'ggH':
    'GluGluHTo2Tau_UncorrelatedDecay_SM_Filtered_ProdAndDecay': {x_sec: 3.276, n_eff: 51778511, filter_eff: 0.3847}
    'GluGluHTo2Tau_UncorrelatedDecay_MM_Filtered_ProdAndDecay': {x_sec: 3.276, n_eff: 51778511, filter_eff: 0.3847}
    'GluGluHTo2Tau_UncorrelatedDecay_CPodd_Filtered_ProdAndDecay': {x_sec: 3.276, n_eff: 51778511, filter_eff: 0.3847}
  # Vector Boson Fusion Higgs Samples
  'VBFH':
    'VBFHToTauTau_UncorrelatedDecay_Filtered': {x_sec: 0.2558, n_eff: 12453012, filter_eff: 0.4095}
  # TTBar Samples
  'TTBar':
    'TTto2L2Nu': {x_sec: 98.04387875606875, n_eff: 47713334.0}
    'TTtoLNu2Q': {x_sec: 405.74895682981236, n_eff: 151416926.0}
    'TTto4Q': {x_sec: 419.8071644141188, n_eff: 104112654.0}
  # Single Top Samples
  'ST':
    'ST_tW_top_2L2Nu': {x_sec: 3.8, n_eff: 4984812.0}
    'ST_tW_antitop_2L2Nu': {x_sec: 3.8, n_eff: 4906798.0}
    'ST_tW_top_LNu2Q': {x_sec: 15.8, n_eff: 9649924.0}
  # W+Jets Samples
  'WJets':
    'WtoLNu_madgraphMLM': {x_sec: 63425.1, n_eff: 191075090.0}
    'WtoLNu_1J_madgraphMLM': {x_sec: 63425.1, n_eff: 191075090.0}
    'WtoLNu_2J_madgraphMLM': {x_sec: 63425.1, n_eff: 191075090.0}
    'WtoLNu_3J_madgraphMLM': {x_sec: 63425.1, n_eff: 191075090.0}
    'WtoLNu_4J_madgraphMLM': {x_sec: 63425.1, n_eff: 191075090.0}
  # Diboson Samples
  'Diboson':
    'WW': {x_sec: 122.27052, n_eff: 33507000.0}
    'WZ': {x_sec: 41.1474, n_eff: 16770000.0}
    'ZZ': {x_sec: 19.431, n_eff: 2517000.0}
  # Tau DATA (nominal cut - mediun)
  'Tau_DATA':
    'Tau_Run2023C_v1': {extrapolation_factor: 1.1 }  #  0.9831255858119907}
    'Tau_Run2023C_v2': {extrapolation_factor: 1.1 }  #  0.9831255858119907}
    'Tau_Run2023C_v3': {extrapolation_factor: 1.1 }  #  0.9831255858119907}
    'Tau_Run2023C_v4': {extrapolation_factor: 1.1 }  #  0.9831255858119907}
  # Tau DATA (tight)
  'Tau_DATA_tight':
    'Tau_Run2023C_v1': {extrapolation_factor: 1.1 }  #  0.9784997982174782}
    'Tau_Run2023C_v2': {extrapolation_factor: 1.1 }  #  0.9784997982174782}
    'Tau_Run2023C_v3': {extrapolation_factor: 1.1 }  #  0.9784997982174782}
    'Tau_Run2023C_v4': {extrapolation_factor: 1.1 }  #  0.9784997982174782}
  # Tau DATA (vtight)
  'Tau_DATA_vtight':
    'Tau_Run2023C_v1': {extrapolation_factor: 1.1 }  #  0.9708573187343692}
    'Tau_Run2023C_v2': {extrapolation_factor: 1.1 }  #  0.9708573187343692}
    'Tau_Run2023C_v3': {extrapolation_factor: 1.1 }  #  0.9708573187343692}
    'Tau_Run2023C_v4': {extrapolation_factor: 1.1 }  #  0.9708573187343692}
  # Muon DATA
  'Muon_DATA':
    'Muon0_Run2023C_v1': {extrapolation_factor: 1.1 }  #  0.6144995181579057}
    'Muon0_Run2023C_v2': {extrapolation_factor: 1.1 }  #  0.6144995181579057}
    'Muon0_Run2023C_v3': {extrapolation_factor: 1.1 }  #  0.6144995181579057}
    'Muon0_Run2023C_v4': {extrapolation_factor: 1.1 }  #  0.6144995181579057}
    'Muon1_Run2023C_v1': {extrapolation_factor: 1.1 }  #  0.6144995181579057}
    'Muon1_Run2023C_v2': {extrapolation_factor: 1.1 }  #  0.6144995181579057}
    'Muon1_Run2023C_v3': {extrapolation_factor: 1.1 }  #  0.6144995181579057}
    'Muon1_Run2023C_v4': {extrapolation_factor: 1.1 }  #  0.6144995181579057}
  # Electron DATA
  'Electron_DATA':
    'EGamma0_Run2023C_v1': {extrapolation_factor: 1.1 }  #  0.7061333828738443}
    'EGamma0_Run2023C_v2': {extrapolation_factor: 1.1 }  #  0.7061333828738443}
    'EGamma0_Run2023C_v3': {extrapolation_factor: 1.1 }  #  0.7061333828738443}
    'EGamma0_Run2023C_v4': {extrapolation_factor: 1.1 }  #  0.7061333828738443}
    'EGamma1_Run2023C_v1': {extrapolation_factor: 1.1 }  #  0.7061333828738443}
    'EGamma1_Run2023C_v2': {extrapolation_factor: 1.1 }  #  0.7061333828738443}
    'EGamma1_Run2023C_v3': {extrapolation_factor: 1.1 }  #  0.7061333828738443}
    'EGamma1_Run2023C_v4': {extrapolation_factor: 1.1 }  #  0.7061333828738443}

